version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: nashdeporti-mongo
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data

volumes:
  mongo-data:
